# workflow name
name: CI/CD Pipeline
on:
  # Manually trigger workflow name
  workflow_dispatch:
  # Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  # Test's job
  tests:
    name: Unit test
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    # Jobs's steps
    steps:
      # check-out repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      # set up jdk11
      - name: set up JDK
        uses: actions/setup-java@v1
        with: 
          java-version: '11'
      # set up maven cache
      - name: cache maven packages
        # this action allows caching dependencies and build outputs to improve workflow execution time
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Run Tests
      - name: Run Tests
        run: mvn -B test